language: php

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
before_script :
  - composer install
  - mysql -e 'create database active_record_migrations_test;'
  - mysql -e "use mysql; SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis'); FLUSH PRIVILEGES;"

after_script:
  - CODECLIMATE_REPO_TOKEN="e14841f1224623da44df1fa624c3680770a9dd3f75a1ff4614b5cf432ecd315c" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

script:
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 *.php ar_migrate src tests
  - phpunit
notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY
