#!/usr/bin/env php
<?php
/*
 * This file is based on part of PHPUnit.
 */

if (!ini_get('date.timezone')) {
	ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
	if (file_exists($file)) {
		define('ACTIVERECORDMIGRATIONS_COMPOSER_INSTALL', $file);
		break;
	}
}

unset($file);

if (!defined('ACTIVERECORDMIGRATIONS_COMPOSER_INSTALL')) {
	fwrite(STDERR,
		'You need to set up the project dependencies using the following commands:' . PHP_EOL .
		'wget http://getcomposer.org/composer.phar' . PHP_EOL .
		'php composer.phar install' . PHP_EOL
	);
	die(1);
}

define("ACTIVERECORDMIGRATIONS_CWD", getcwd());

require ACTIVERECORDMIGRATIONS_COMPOSER_INSTALL;

$bootstrap = dirname(ACTIVERECORDMIGRATIONS_COMPOSER_INSTALL) . "/../bootstrap.php";
require $bootstrap;

\Thru\ActiveRecordMigrations\Migrator::Main();